# Anka-Tech-Case/docker-compose.yml
version: '3.8' # Pode ser omitido

services:
  db:
    image: mysql:8.0
    container_name: anka-app-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - anka_mysql_data:/var/lib/mysql
    networks:
      - anka_network

  backend:
    build:
      context: ./anka-tech-backend # Caminho para a pasta do backend
      dockerfile: Dockerfile
    container_name: anka-app-backend-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:userpassword@db:3306/mydb" # Conecta ao serviço 'db'
      # Adicione outras variáveis de ambiente do backend aqui
    volumes:
      - ./anka-tech-backend:/usr/src/app # Mapeia código para dev (hot reload)
      - /usr/src/app/node_modules
    networks:
      - anka_network

  frontend:
    build:
      context: ./anka-tech-frontend
      dockerfile: Dockerfile
      args:
        # Altere esta URL para ser acessível pelo navegador do host
        NEXT_PUBLIC_API_URL: http://localhost:3001/api # <--- CORRIGIDO
    container_name: anka-app-frontend-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./anka-tech-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - anka_network

volumes:
  anka_mysql_data:

networks: # Define uma rede customizada para os serviços se comunicarem
  anka_network:
    driver: bridge